[package]
name = "unifed-fedtree"
version = "0.0.0"
keywords = ["federated learning", "machine learning"]
description = "FedTree."
language = "python"
install_script = """
if { conda env list | grep 'colink-protocol-unifed-fedtree'; } >/dev/null 2>&1; then
    conda env remove -n colink-protocol-unifed-fedtree
fi
conda create -n colink-protocol-unifed-fedtree python=3.9 -y
conda activate colink-protocol-unifed-fedtree
pip install .
"""
entrypoint = """
conda activate colink-protocol-unifed-fedtree
unifed-fedtree > ./debug.txt 2>&1
"""
